# Problem 1: угадать рандомное число от 1 до 100

In [1]:
import random

def random_guess():
    
    x = random.randint(1, 100)
    
    a = int(input('Введите число: '))
    
    if a == x:
        print('Верно!')
        return
    
    while a != x:
        
        if x < a:
            a = int(input("Нужное число меньше Вашего, введите другое: "))
            
        elif x > a:
            a = int(input("Нужное число больше Вашего, введите другое: "))
            
        if a == x:
            print('Верно!')
            
    return

In [2]:
random_guess()

Введите число: 54
Нужное число больше Вашего, введите другое: 77
Нужное число меньше Вашего, введите другое: 70
Нужное число меньше Вашего, введите другое: 60
Верно!


# Problem 2: генератор пароля

In [3]:
def generate_password(length):
    
    digits = '0123456789'
    small_letters = 'abcdefghiklmnopqrstvxyz'
    letters = 'ABCDEFGHIKLMNOPQRSTVXYZ'
    symbols = '!@#$%^&*()_+'
    
    password = ''
    
    var = [digits, small_letters, letters, symbols]
    
    if length < 12:
        print('Пароль должен иметь не менее 12 симолов')
        return
    
    while len(password) < length:
        password += random.choice(var[random.randint(0,3)])
  
    print(password)
    #return

In [4]:
generate_password(12)

F8VMc(1v2HO)


In [5]:
import random

def generate_password_2():
    
    l = int(input('Длина пароля: '))

    password = ''
    
    for i in range(l):
        a = random.randint(33, 126)
        password += chr(a)

    print(password)

In [6]:
generate_password_2()

Длина пароля: 7
3a2rjRF


# Бинарный поиск

In [7]:
def binary_search(numbers, target):
    
    start = 0
    end = len(numbers)
    
    while start <= end:
        
        mid = (start + end) // 2
        
        if target == numbers[mid]:
            return mid
        
        if target < numbers[mid]:
            end = mid - 1
            
        else:
            start = mid + 1

In [8]:
numbers = [2,7,11,15]
target = 7

print(binary_search(numbers, target))

1


In [9]:
def twoSum(nums, target):
        
        #binary search
        
        nums = sorted(enumerate(nums), key=lambda i: i[1])
        
        a = 0 
        b = len(nums) - 1
        
        print(b)
        print(nums)
        
        while a < b:
            s = nums[a][1] + nums[b][1]
            
            if s > target:
                b -= 1
                
            if s < target:
                a += 1
                
            if s == target:
                return nums[a][0], nums[b][0]

In [10]:
nums = [3,3]
target = 6
print(twoSum(nums, target))

1
[(0, 3), (1, 3)]
(0, 1)


# Классы

In [11]:
class Circle(): # в классепишутся методы(функции)
    def __init__(self, R=10): #вызывается, когда создаётся объект class, мы можем передавать в init параметры для объекта
        self.R = R
        self._a = R*100 
    
    def square(self): 
        
        return 3.14 * self.R**2
    
    def unk_func():
        
        return self._a
    
    def __lt__(self, other_circle):
        
        return self.R < other_circle.R
    
    def __str__(self):
        
        return f'circle of radius {self.R}'
    
    def __repr__(self): # representation
        
        return f'circle of radius {self.R}'

In [12]:
c = Circle()

print('Радиус: ', c.R)  
print('Площадь: ', c.square()) # метод

Радиус:  10
Площадь:  314.0


In [13]:
 c.R # атрибут

10

In [14]:
c.square() # метод

314.0

In [15]:
c._a

1000

В питоне нет скрытых переменных, в отличие от c++, в котором помимо public переменных есть ещё private переменные

In [16]:
dir(c)

['R',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_a',
 'square',
 'unk_func']

In [17]:
cc = [Circle(R=1), Circle(R=14), Circle(R=13), Circle(R=6)]
cc

[circle of radius 1,
 circle of radius 14,
 circle of radius 13,
 circle of radius 6]

# Сортировка

In [ ]:
# библиотека для реализации очереди: https://docs.python.org/3/library/queue.html

In [19]:
a = [2,1,23,11,32,15]
sorted(a)

[1, 2, 11, 15, 23, 32]

In [20]:
a = [2,1,23,11,'32',15]
sorted(a)               # мы не можем сравнивать разные типы данных

TypeError: '<' not supported between instances of 'str' and 'int'

In [21]:
a = [2,1,23,11,'32',15]
sorted(a, key=lambda x:int(x))  

[1, 2, 11, 15, 23, '32']

In [22]:
a = [2,1,23,11,'32',15]
sorted(a, key=lambda x:str(x))   # сортировка в лексик-графическом порядке

[1, 11, 15, 2, 23, '32']

# Список атрибутов и методов объекта

В вашем случае, b - это целочисленная переменная со значением 100, и dir(b) вернет список атрибутов и методов, доступных для объекта типа int (целое число).

In [85]:
b = 100
dir(b)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [24]:
b.__lt__(1000) # less then

True

In [26]:
b.__gt__(1000) # greater then

False

In [27]:
b.__le__(1000) # less or equal

True

In [28]:
b.__ge__(1000) # greater or equal

False

# Словари

In [29]:
def dict_from_keys_and_values(keys, values):
    
    d = {}
    
    #for k in keys:
    for i in range(len(keys)):
        if i < len(values):
            d[keys[i]] = values[i]
        else:
            d[keys[i]] = None
            
    return d

In [30]:
keys = [1, 2, 3, 4, 5]
values = ['1', '2', '3']

dict_from_keys_and_values(keys, values)

{1: '1', 2: '2', 3: '3', 4: None, 5: None}

In [31]:
keys = [1, 2, 3]
values = ['1', '2', '3', '4', '5']

dict_from_keys_and_values(keys, values)

{1: '1', 2: '2', 3: '3'}

# Списки и срезы

In [32]:
import numpy as np

1. Четные индексы 

In [33]:
print(np.arange(1, 6)[::2])

[1 3 5]


In [34]:
print(' '.join(input().split()[::2]))

1 65 36 84 57
1 36 57


2. Наибольший элемент и его индекс

In [35]:
A = [1, 2, 3, 2, 1]

print(np.max(A), np.argmax(A))

3 2


In [36]:
A = input().split()

print(max(A), A.index(max(A)))

1 2 3 2 1
3 2


3. Вывести в обратном порядке

In [37]:
print(np.arange(1, 6)[::-1])

[5 4 3 2 1]


In [38]:
print(' '.join(input().split()[::-1]))

1 2 3 4 5
5 4 3 2 1


4. Переставить соседние 

In [42]:
A = input().split()

if len(A) % 2 == 0:
    A[::2], A[1::2] = A[1::2], A[::2]
else:
    A[:-1:2], A[1::2] = A[1::2], A[:-1:2]

print(' '.join(A))

2 1 4 3 6 5
1 2 3 4 5 6


5. Циклический сдвиг вправо

In [43]:
A = np.arange(1, 6)

print(np.roll(A, 1))

[5 1 2 3 4]


6. Удалить элемент

In [45]:
A = [7, 6, 5, 4, 3, 2, 1]

print(np.delete(A, [2, 6]))

[7 6 4 3 2]


7. Вставить элемент

In [46]:
A = [7, 6, 5, 4, 3, 2, 1]

print(np.insert(A, 2, 0))

[7 6 0 5 4 3 2 1]


8. Большой сдвиг

In [49]:
A = [5, 3, 7, 4, 6]

print(np.roll(A, 3))

[7 4 6 5 3]
